### ISSUE TITLE
wakelock forces me to use old versions of plugins

### ISSUE THREAD

**Issue by kostadin24** [creativecreatorormaybenot/wakelock#198]
Can we have plugin dependencies updated, please?

**Comment by MrCsabaToth** [comment]
Yes please!

**Comment by armandojimenez** [comment]
Any updates on this? Can use this with Dart 3 & Flutter 3.10

**Comment by nilsreichardt** [comment]
> Any updates on this? Can use this with Dart 3 & Flutter 3.10

You can use this package with Dart 3 & Flutter 3.10. However, you might have some dependencies that depend on `win32 >3.0.0`. In this case, you need to use the following override in your `pubspec.yaml`:

```yaml
dependency_overrides:
  # Can be removed when
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203 is merged.
  wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock
      ref: win32-v5
      path: wakelock_windows
```
