### ISSUE TITLE
Wakelock pub get problem

### ISSUE THREAD

**Issue by cnkygmr** [creativecreatorormaybenot/wakelock#202]
```
Resolving dependencies...
Because no versions of wakelock_windows match >0.2.1 <0.3.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, wakelock_windows <0.2.1-∞ or >0.2.1 <0.3.0 requires win32 ^2.0.0.
And because wakelock_windows 0.2.1 depends on win32 ^3.0.0, wakelock_windows <0.3.0 requires win32 ^2.0.0 or ^3.0.0.
Because no versions of wakelock match >0.6.2 <0.7.0 and wakelock 0.6.2 depends on wakelock_windows ^0.2.0, wakelock ^0.6.2 requires wakelock_windows ^0.2.0.
Thus, wakelock ^0.6.2 requires win32 ^2.0.0 or ^3.0.0.
And because device_info_plus >=9.0.0 depends on win32 ^4.1.4, wakelock ^0.6.2 is incompatible with device_info_plus >=9.0.0.
So, because xxx depends on both device_info_plus ^9.0.0 and wakelock ^0.6.2, version solving failed.
Process finished with exit code 1
```

**Comment by miguelmato** [comment]
And me blaming win32...

Honestly, if I use Flutter only for mobile, it would be nice if packages could differentiate dependencies based on supported platforms. I know it's a lot of work for little gains, but it could be interesting.

**Comment by BrahimAkar** [comment]
same problem 😥

**Comment by miguelmato** [comment]
I forked the package and removed the web and desktop platforms as I don't need them. You can do the same or just bump the dependencies versions as you need.

In your project pubspec.yaml:
`wakelock: 
    git:
      url: https://github.com/<YOUR_GH_USERNAME>/wakelock
      ref: main
      path: wakelock`

**Comment by NashIlli** [comment]
+1

**Comment by ps6067966** [comment]
facing same issue.

**Comment by nilsreichardt** [comment]
I recommend to override `wakelock_winodws`:

```yaml
dependency_overrides:
  # Can be removed when
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203 is merged.
  wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock
      ref: win32-v5
      path: wakelock_windows
```

**Comment by ozzy1873** [comment]
@miguelmato I am using your fork, but there is an unmatched '}' on line 23 of wakelock.dart.

**Comment by miguelmato** [comment]
> @miguelmato I am using your fork, but there is an unmatched '}' on line 23 of wakelock.dart.

Fixed, but the @nilsreichardt approach is nicer

**Comment by ozzy1873** [comment]
Thanks!

**Comment by nilsreichardt** [comment]
@dgilperez You can use the project by @diegotori

```yaml
dependency_overrides:
  # Can be removed when
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203 is merged.
  wakelock_windows:
    git:
      url: https://github.com/diegotori/wakelock
      ref: 40464c75e908f57f458597ef4912f5273ab89b1a
      path: wakelock_windows
```
