### ISSUE TITLE
Wakelock doesn't work at the latest version of flutter

### ISSUE THREAD

**Issue by sarakhater** [creativecreatorormaybenot/wakelock#211]
Our  flutter app closed although we are using Wakelock package at the latest version of flutter .
the old version is working normally.
Could you support me?

**Comment by vanlooverenkoen** [comment]
For now, I just use: 
```
dependency_overrides:
  win32: 3.1.4
```
because that was the dependency that was causing issues.

**Comment by kamyar75** [comment]
I am having this problem and I don't know what to do

**Comment by XHZ360** [comment]
We have also encountered the same issue

**Comment by Goddchen** [comment]
Also this part will be an issue since Flutter 3.10 uses Dart >=3.

```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'
```

**Comment by martin-formigas** [comment]
For a temporary workaround, I have forked the repo and upgraded the dependency constraints. If you want to use it until an official update is available:

```yaml
dependency_overrides:
  wakelock_windows:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock_windows/
      ref: main
```

```yaml
dependencies:
  wakelock:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock/
      ref: main
```

**Comment by martin-formigas** [comment]
Also created this as a PR: https://github.com/creativecreatorormaybenot/wakelock/pull/213

**Comment by dj-yacine-flutter** [comment]
> ```yaml
> github.com:formigas/wakelock
> ```

how to use your version now because i need it

**Comment by aytunch** [comment]
@martin-formigas 
The project I am working on is not using wakelock directly but some of the packages we have are using it.
How can I use your fork to overcome this? I tried the above suggested solution

```
environment:
  sdk: '>=2.12.0 <3.0.0'
```

But it gave errors on pub get.

**Comment by Goddchen** [comment]
@aytunch you can override it even when it is only a transitive dependency. Just use `dependency_overrides` instead of `dependencies`.

```dart
dependency_overrides:
  wakelock:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock/
      ref: main
```

**Comment by aytunch** [comment]
Hi @Goddchen thanks for the info.
This is what I added to my pubspec.yaml and I get the below error.
If I downgrade the `pod_player` to 0.0.6, then I can do pub get but app crashes when wakelock is used in the podplayer package with the new Flutter 3.10.5.
Can I solve this by `dependency_overrides` magic?

```
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0-beta.22
  # https://pub.dev/packages/pod_player
  pod_player: ^0.1.5

dependency_overrides:
  wakelock:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock/
      ref: main
  wakelock_windows:
    git:
      url: git@github.com:formigas/wakelock.git
      path: wakelock_windows/
      ref: main
```

```
Resolving dependencies...
Because every version of core from path depends on package_info_plus ^4.0.2 and no versions of package_info_plus match >4.0.2 <5.0.0, every version of core from path requires package_info_plus 4.0.2.
And because package_info_plus 4.0.2 depends on win32 >=4.0.0 <6.0.0, every version of core from path requires win32 >=4.0.0 <6.0.0.
Because wakelock_windows >=0.2.1 depends on win32 ^3.0.0 and wakelock_windows <0.2.1 depends on win32 ^2.0.0, every version of wakelock_windows requires win32 ^2.0.0 or ^3.0.0.
Thus, core from path is incompatible with wakelock_windows.
And because pod_player >=0.1.1 depends on wakelock ^0.6.2 which depends on wakelock_windows ^0.2.0, core from path is incompatible with pod_player >=0.1.1.
So, because insurance depends on both pod_player ^0.1.5 and core from path, version solving failed.
exit code 1
```

**Comment by aytunch** [comment]
Moreover, I don't see `wakelock_windows` in my pubspec.lock files. This is the generated lock:

```
  wakelock:
    dependency: transitive
    description:
      name: wakelock
      sha256: "78bad4822be81d37e7bc34b6990da7dface2a445255cd37c6f053b51a4ccdb3b"
      url: "https://pub.dev"
    source: hosted
    version: "0.4.0"
  wakelock_macos:
    dependency: transitive
    description:
      name: wakelock_macos
      sha256: "73581e5d9ed2dd1ba951375c30e63f0eb8c58d7d6286ae9ddf927b88f2aea8d9"
      url: "https://pub.dev"
    source: hosted
    version: "0.1.0+3"
  wakelock_platform_interface:
    dependency: transitive
    description:
      name: wakelock_platform_interface
      sha256: d0a8a1c02af68077db5df1e0f5e2b745f7b1f2cdcc48e3e0b6f8f4dcc349050e
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1+3"
  wakelock_web:
    dependency: transitive
    description:
      name: wakelock_web
      sha256: "06b0033d5421712138e7fa482ff5c6280fe12e0a41c40c3fe8fda2c007eb4348"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0+3"
```
